// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-w3IDluNUcJ8PnOl0AaWjhcNUkw-qgko',
    appId: '1:105617353219:web:f26db69f5f493ee50ffc36',
    messagingSenderId: '105617353219',
    projectId: 'ai-content-detector-2d3b3',
    authDomain: 'ai-content-detector-2d3b3.firebaseapp.com',
    storageBucket: 'ai-content-detector-2d3b3.firebasestorage.app',
    measurementId: 'G-G4TEZMFXH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTMdcOcOps3POQfuiu-mWg-sZLyynWLqA',
    appId: '1:105617353219:android:df8f264d4022acd40ffc36',
    messagingSenderId: '105617353219',
    projectId: 'ai-content-detector-2d3b3',
    storageBucket: 'ai-content-detector-2d3b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcIZHhPptzhg-1AZCtSX1x7agIBudf31o',
    appId: '1:105617353219:ios:d481da39f72cfb590ffc36',
    messagingSenderId: '105617353219',
    projectId: 'ai-content-detector-2d3b3',
    storageBucket: 'ai-content-detector-2d3b3.firebasestorage.app',
    iosBundleId: 'com.example.aiContentDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcIZHhPptzhg-1AZCtSX1x7agIBudf31o',
    appId: '1:105617353219:ios:d481da39f72cfb590ffc36',
    messagingSenderId: '105617353219',
    projectId: 'ai-content-detector-2d3b3',
    storageBucket: 'ai-content-detector-2d3b3.firebasestorage.app',
    iosBundleId: 'com.example.aiContentDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-w3IDluNUcJ8PnOl0AaWjhcNUkw-qgko',
    appId: '1:105617353219:web:6d55142dece986d30ffc36',
    messagingSenderId: '105617353219',
    projectId: 'ai-content-detector-2d3b3',
    authDomain: 'ai-content-detector-2d3b3.firebaseapp.com',
    storageBucket: 'ai-content-detector-2d3b3.firebasestorage.app',
    measurementId: 'G-TQW14SC8CX',
  );

}
